/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef RpcService_H
#define RpcService_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include "t_types.h"



#ifdef _WIN32
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class RpcServiceIf {
 public:
  virtual ~RpcServiceIf() {}
  virtual void TwoWayCall(std::string& _return, const std::string& input) = 0;
};

class RpcServiceIfFactory {
 public:
  typedef RpcServiceIf Handler;

  virtual ~RpcServiceIfFactory() {}

  virtual RpcServiceIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(RpcServiceIf* /* handler */) = 0;
};

class RpcServiceIfSingletonFactory : virtual public RpcServiceIfFactory {
 public:
  RpcServiceIfSingletonFactory(const boost::shared_ptr<RpcServiceIf>& iface) : iface_(iface) {}
  virtual ~RpcServiceIfSingletonFactory() {}

  virtual RpcServiceIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(RpcServiceIf* /* handler */) {}

 protected:
  boost::shared_ptr<RpcServiceIf> iface_;
};

class RpcServiceNull : virtual public RpcServiceIf {
 public:
  virtual ~RpcServiceNull() {}
  void TwoWayCall(std::string& /* _return */, const std::string& /* input */) {
    return;
  }
};

typedef struct _RpcService_TwoWayCall_args__isset {
  _RpcService_TwoWayCall_args__isset() : input(false) {}
  bool input :1;
} _RpcService_TwoWayCall_args__isset;

class RpcService_TwoWayCall_args {
 public:

  RpcService_TwoWayCall_args(const RpcService_TwoWayCall_args&);
  RpcService_TwoWayCall_args& operator=(const RpcService_TwoWayCall_args&);
  RpcService_TwoWayCall_args() : input() {
  }

  virtual ~RpcService_TwoWayCall_args() throw();
  std::string input;

  _RpcService_TwoWayCall_args__isset __isset;

  void __set_input(const std::string& val);

  bool operator == (const RpcService_TwoWayCall_args & rhs) const
  {
    if (!(input == rhs.input))
      return false;
    return true;
  }
  bool operator != (const RpcService_TwoWayCall_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const RpcService_TwoWayCall_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class RpcService_TwoWayCall_pargs {
 public:


  virtual ~RpcService_TwoWayCall_pargs() throw();
  const std::string* input;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _RpcService_TwoWayCall_result__isset {
  _RpcService_TwoWayCall_result__isset() : success(false) {}
  bool success :1;
} _RpcService_TwoWayCall_result__isset;

class RpcService_TwoWayCall_result {
 public:

  RpcService_TwoWayCall_result(const RpcService_TwoWayCall_result&);
  RpcService_TwoWayCall_result& operator=(const RpcService_TwoWayCall_result&);
  RpcService_TwoWayCall_result() : success() {
  }

  virtual ~RpcService_TwoWayCall_result() throw();
  std::string success;

  _RpcService_TwoWayCall_result__isset __isset;

  void __set_success(const std::string& val);

  bool operator == (const RpcService_TwoWayCall_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const RpcService_TwoWayCall_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const RpcService_TwoWayCall_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _RpcService_TwoWayCall_presult__isset {
  _RpcService_TwoWayCall_presult__isset() : success(false) {}
  bool success :1;
} _RpcService_TwoWayCall_presult__isset;

class RpcService_TwoWayCall_presult {
 public:


  virtual ~RpcService_TwoWayCall_presult() throw();
  std::string* success;

  _RpcService_TwoWayCall_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class RpcServiceClient : virtual public RpcServiceIf {
 public:
  RpcServiceClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  RpcServiceClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void TwoWayCall(std::string& _return, const std::string& input);
  void send_TwoWayCall(const std::string& input);
  void recv_TwoWayCall(std::string& _return);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class RpcServiceProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<RpcServiceIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (RpcServiceProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_TwoWayCall(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  RpcServiceProcessor(boost::shared_ptr<RpcServiceIf> iface) :
    iface_(iface) {
    processMap_["TwoWayCall"] = &RpcServiceProcessor::process_TwoWayCall;
  }

  virtual ~RpcServiceProcessor() {}
};

class RpcServiceProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  RpcServiceProcessorFactory(const ::boost::shared_ptr< RpcServiceIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< RpcServiceIfFactory > handlerFactory_;
};

class RpcServiceMultiface : virtual public RpcServiceIf {
 public:
  RpcServiceMultiface(std::vector<boost::shared_ptr<RpcServiceIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~RpcServiceMultiface() {}
 protected:
  std::vector<boost::shared_ptr<RpcServiceIf> > ifaces_;
  RpcServiceMultiface() {}
  void add(boost::shared_ptr<RpcServiceIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void TwoWayCall(std::string& _return, const std::string& input) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->TwoWayCall(_return, input);
    }
    ifaces_[i]->TwoWayCall(_return, input);
    return;
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class RpcServiceConcurrentClient : virtual public RpcServiceIf {
 public:
  RpcServiceConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  RpcServiceConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void TwoWayCall(std::string& _return, const std::string& input);
  int32_t send_TwoWayCall(const std::string& input);
  void recv_TwoWayCall(std::string& _return, const int32_t seqid);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  ::apache::thrift::async::TConcurrentClientSyncInfo sync_;
};

#ifdef _WIN32
  #pragma warning( pop )
#endif



#endif
