/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef t_CONSTANTS_H
#define t_CONSTANTS_H

#include "t_types.h"



class tConstants {
 public:
  tConstants();

};

extern const tConstants g_t_constants;



#endif
