// Code generated by protoc-gen-go.
// source: test.pb
// DO NOT EDIT!

/*
Package user_info is a generated protocol buffer package.

It is generated from these files:
	test.pb

It has these top-level messages:
	UserInfo
*/
package user_info

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UserInfo struct {
	Uid              *uint64 `protobuf:"varint,1,req,name=uid" json:"uid,omitempty"`
	Name             *string `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	Nickname         *string `protobuf:"bytes,3,opt,name=nickname" json:"nickname,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *UserInfo) Reset()                    { *m = UserInfo{} }
func (m *UserInfo) String() string            { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()               {}
func (*UserInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *UserInfo) GetUid() uint64 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *UserInfo) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *UserInfo) GetNickname() string {
	if m != nil && m.Nickname != nil {
		return *m.Nickname
	}
	return ""
}

func init() {
	proto.RegisterType((*UserInfo)(nil), "user_info.userInfo")
}

func init() { proto.RegisterFile("test.pb", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 93 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x62, 0x2f, 0x49, 0x2d, 0x2e,
	0xd1, 0x2b, 0x48, 0x12, 0xe2, 0x2c, 0x2d, 0x4e, 0x2d, 0x8a, 0xcf, 0xcc, 0x4b, 0xcb, 0x57, 0x32,
	0xe7, 0xe2, 0x00, 0x71, 0x3c, 0x81, 0x6c, 0x21, 0x6e, 0x2e, 0xe6, 0xd2, 0xcc, 0x14, 0x09, 0x46,
	0x05, 0x26, 0x0d, 0x16, 0x21, 0x1e, 0x2e, 0x96, 0xbc, 0xc4, 0xdc, 0x54, 0x09, 0x26, 0x20, 0x8f,
	0x53, 0x48, 0x80, 0x8b, 0x23, 0x2f, 0x33, 0x39, 0x1b, 0x2c, 0xc2, 0xac, 0xc0, 0xa8, 0xc1, 0x09,
	0x08, 0x00, 0x00, 0xff, 0xff, 0x4e, 0x9a, 0xf1, 0x59, 0x4d, 0x00, 0x00, 0x00,
}
